function valid = checkmastruct(maStruct)
% CHECKMASTRUCT checks for standard mastruct types
%
% Currently supported: GenePix, Imagene, SPOT

% Copyright 2003-2005 The MathWorks, Inc.

valid =  isfield(maStruct,'Header')&& isfield(maStruct.Header,'Type') && ...
        (~isempty(strfind(maStruct.Header.Type,'GenePix')) ...
        || ~isempty(strfind(maStruct.Header.Type,'FeatureExtractor'))...
        || ~isempty(strfind(maStruct.Header.Type,'SPOT'))...
        || ~isempty(strfind(maStruct.Header.Type,'ImaGene')));
