function hgSetup(h)
%HGSETUP


% Copyright 2003-2004 The MathWorks, Inc.

if isempty(h.up) || ~isequal(class(h.up),'biograph.bggui')
    error(message('bioinfo:biograph:hgSetup:nobggui'));
end

% creates the HG elements and store handles into biograph info
h.hgAxes = axes('Units','points',...
                'Position',[0 0 1 1],... 
                'XTick',[],...
                'YTick',[],...
                'XColor',[1 1 1],...
                'YColor',[1 1 1],...
                'Box','off',...
                'NextPlot','add',...
                'Visible','off');

% update rendering with info from layout
h.hgUpdate

       
