%PREFSPANEL Registers a preferences control panel.
%   PREFSPANEL registers a Preferences Control panel with the MATLAB IDE.
%

%   Copyright 2003-2005 The MathWorks, Inc.


com.mathworks.mlwidgets.workspace.MatlabCustomClassRegistry.registerClassCallbacks(...
    'phytree',...
    'Phylogenetic tree',...
    {'Export to Newick','Print to Figure'},...
    {'phytreewrite($1,''GUI'',true);','plot($1);'} );
